micronaut:
  application:
    name: pixRest

grpc:
  client:
    plaintext: true
    max-retry-attemps: 10
  channels:
    KeyManager:
      address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}'

jackson:
  serialization:
    writeDatesAsTimestamps: false